spring.application.name=auth
# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/ForumAuth
spring.datasource.username=postgres
spring.datasource.password=changeme

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

amqp.url = amqps://opqzgyoy:QbrQbz_pnUwVMFvHS6m0GEvVNpqMZQRv@cow.rmq2.cloudamqp.com/opqzgyoy
amqp.password = QbrQbz_pnUwVMFvHS6m0GEvVNpqMZQRv

# Filebase/AwsS3BucketStorage
aws.region = us-east-1
aws.key.access = 1BE8C124B53641016201
aws.key.secret = 2B8s3JCdPwiFaBgp5ZdENRvwTyTYGU8CbYp26lH0
filebase.endpoint = https://s3.filebase.com/
filebase.bucket.name = photos-bucket
filebase.gateway.name = https://compatible-amaranth-antelope.myfilebase.com/ipfs/
